name: flutterban
description: A Kanban board built in Flutter

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  uuid: ^4.5.1
  flutter_bloc: ^8.1.2
  flutter_mobx: ^2.0.6+5
  provider: ^6.0.5
  http: ^1.2.2
  dio: ^5.7.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  intl: ^0.19.0
  hijri: ^3.0.0
  file_picker: ^6.0.0
  shared_preferences: 2.2.3
  dropdown_search: ^6.0.1
  # bangla_utilities: ^1.5.0
  # bangla_date: ^1.0.1

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  mobx_codegen: ^2.2.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.otf
        - asset: assets/fonts/Montserrat-Medium.otf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.otf
        - asset: assets/fonts/Montserrat-SemiBold.otf

    - family: NotoSansBengali
      fonts:
        - asset: assets/fonts/NotoSansBengali-Regular.ttf

    - family: NotoSansArabic
      fonts:
        - asset: assets/fonts/NotoSansArabic-Regular.ttf

  assets:
    - assets/icons/app_icon.png
    - assets/icons/task_management.png
    - assets/icons/muhsina.jpeg
